# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliply', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='price',
        ),
    ]
